apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: |
      [{"apiVersion":"apps/v1","kind":"Deployment","name":"inventory"},{"apiVersion":"apps/v1","kind":"Deployment","name":"catalog-database"}]
  labels:
    app.kubernetes.io/instance: globex-app
    app.kubernetes.io/name: catalog
    app.kubernetes.io/part-of: globex-app
    app.openshift.io/runtime: spring
  name: catalog
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog
      app.kubernetes.io/part-of: globex-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalog
        app.kubernetes.io/part-of: globex-app
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: catalog-database
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: catalog-database
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: catalog-database
        - name: JAVA_OPTIONS
          value: -Dspring.profiles.active=openshift
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://catalog-database:5432/${POSTGRESQL_DATABASE}
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: database-user
              name: catalog-database
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: catalog-database
        - name: INVENTORY_URL
          value: inventory:8080
        image: quay.io/redhat-gpte/globex-catalog:app-mod-workshop
        imagePullPolicy: IfNotPresent
        name: catalog
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: catalog-app
      serviceAccountName: catalog-app
      terminationGracePeriodSeconds: 30
