apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: |
      [{"apiVersion":"apps/v1","kind":"Deployment","name":"inventory-database"}]
  labels:
    app.kubernetes.io/instance: globex-app
    app.kubernetes.io/name: inventory
    app.kubernetes.io/part-of: globex-app
    app.kubernetes.io/version: 1.0.0
    app.openshift.io/runtime: quarkus
  name: inventory
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory
      app.kubernetes.io/part-of: globex-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: inventory
        app.kubernetes.io/part-of: globex-app
    spec:
      containers:
      - env:
        - name: QUARKUS_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: database-user
              name: inventory-database
        - name: QUARKUS_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: inventory-database
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: inventory-database
        - name: QUARKUS_DATASOURCE_JDBC_URL
          value: jdbc:postgresql://inventory-database:5432/${POSTGRESQL_DATABASE}
        image: quay.io/redhat-gpte/globex-inventory:app-mod-workshop
        imagePullPolicy: IfNotPresent
        name: inventory
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: inventory-app
      serviceAccountName: inventory-app
      terminationGracePeriodSeconds: 30
