apiVersion: v1
data:
  database-name: Y2F0YWxvZw==
  database-password: Y2F0YWxvZw==
  database-user: Y2F0YWxvZw==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: globex-app
    app.kubernetes.io/name: catalog-database
    app.kubernetes.io/part-of: globex-app
    app.kubernetes.io/version: 1.0.0
  name: catalog-database
type: Opaque
