apiVersion: v1
data:
  application.properties: cXVhcmt1cy5rYWZrYS1zdHJlYW1zLmFwcGxpY2F0aW9uLWlkPWdsb2JleC5yZWNvbW1lbmRhdGlvbgpxdWFya3VzLmthZmthLXN0cmVhbXMudG9waWNzPWdsb2JleC50cmFja2luZwpxdWFya3VzLmthZmthLXN0cmVhbXMuY29tbWl0LmludGVydmFsLm1zPTEwMDAwCmthZmthLXN0cmVhbXMucmVwbGljYXRpb24uZmFjdG9yPTEKdHJhY2tpbmctZXZlbnQtdG9waWM9Z2xvYmV4LnRyYWNraW5nCmthZmthLmJvb3RzdHJhcC5zZXJ2ZXJzPWthZmthLWNsdXN0ZXIta2Fma2EtYm9vdHN0cmFwLmthZmthOjkwOTI=
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: globex-app
    app.kubernetes.io/name: recommendation-engine
    app.kubernetes.io/part-of: globex-app
    app.kubernetes.io/version: 1.0.0
  name: recommendation-engine
type: Opaque
