apiVersion: v1
data:
  application.properties: bXAubWVzc2FnaW5nLm91dGdvaW5nLm9yZGVyLWV2ZW50LnRvcGljPWdsb2JleC5vcmRlcnMKa2Fma2EuYm9vdHN0cmFwLnNlcnZlcnM9a2Fma2EtY2x1c3Rlci1rYWZrYS1ib290c3RyYXAua2Fma2E6OTA5Mg==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: globex-app
    app.kubernetes.io/name: order-placement
    app.kubernetes.io/part-of: globex-app
    app.kubernetes.io/version: 1.0.0
  name: order-placement
type: Opaque
