apiVersion: v1
data:
  database-name: aW52ZW50b3J5
  database-password: aW52ZW50b3J5
  database-user: aW52ZW50b3J5
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: globex-app
    app.kubernetes.io/name: inventory-database
    app.kubernetes.io/part-of: globex-app
    app.kubernetes.io/version: 1.0.0
  name: inventory-database
type: Opaque
