apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: globex-app
    app.kubernetes.io/name: inventory-database
    app.kubernetes.io/part-of: globex-app
    app.kubernetes.io/version: 1.0.0
  name: inventory-database
spec:
  ports:
  - name: postgresql
    port: 5432
  selector:
    app.kubernetes.io/name: inventory-database
    app.kubernetes.io/part-of: globex-app
