apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: globex-app
    app.kubernetes.io/name: catalog
    app.kubernetes.io/part-of: globex-app
  name: catalog
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/part-of: globex-app
