apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: globex-app
    app.kubernetes.io/name: catalog-database
    app.kubernetes.io/part-of: catalog-app
  name: catalog-database
spec:
  ports:
  - name: postgresql
    port: 5432
  selector:
    app.kubernetes.io/name: catalog-database
    app.kubernetes.io/part-of: globex-app
