bases:
- ../../base
patches:
- target:
    kind: Deployment
    name: globex-ui
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value:                               "quay.io/tjungbau/secure-supply-chain-demo:main-da33e1ea27310f3ab9610241304f9883f5841418"